### ISSUE TITLE
Return statement never reached in load_for_cache

### ISSUE THREAD

**Issue by jnlar** [catalyst/moodle-format_twocol#24]
A new return statement was added to `header_course_image` in https://github.com/catalyst/moodle-format_twocol/commit/9240072d55958178364885b708a203dd71ce3671 but the old one wasn't removed.

Viewing a course via `course/view.php?id=123` throws the following exception:
```
Exception - Argument 1 passed to format_twocol\cache\header_course_image::get_image_url_from_overview_files() must be an
instance of stdClass, null given, called in [dirroot]/course/format/twocol/classes/cache/header_course_image.php on line 59
```

**Comment by guillogo** [comment]
Thanks @jnlar merged and closed.
